from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [

    path('profile/<str:user>', views.profile_view,name='profile'),
    path('edit-profile/', views.edit_profile_view,name='edit-profile'),
    path('change_pass/', views.change_pass_view,name='change_pass'),
    path('privacy/', views.privacy_view,name='privacy'),
    path('newsfeed/', views.newsfeed_view,name='newsfeed'),
    path('login/', views.login_view,name='login'),
    path('signup', views.signupView,name='signup'),
    path('logout/', views.logout_view,name='logout'),
    path('post/', views.post,name='post'),
    path('sharepost/', views.sharePost,name='sharepost'),
    path('follow/<int:user_id>/', views.follow,name='follow'),
    path('follow_request/<int:user_id>/', views.follow_request,name='follow_request'),
    path('liker-avatars/<int:post_id>/',views.liker_avatars,name='liker-avatars'),
    path('likers/<int:post_id>/',views.likers,name='likers'),
    path('load_more/<int:post_id>/<int:count>/<int:count2>',views.comments,name='load_more'),
    path('change_image/',views.change_image,name='change_image'),
    path('comment_like/',views.comment_like,name='comment_like'),
    path('delete/',views.delete,name='delete'),
    path('pin-post/',views.pin_post,name='pin_post'),
    path('notification_bell/',views.notification_bell,name='notification_bell'),
    path('single_post/<int:post_id>/',views.post_view,name='single_post'),
    path('followers/<str:user>/',views.followers_view,name='followers'),
    path('followings/<str:user>/',views.followings_view,name='followings'),
    path('follow-requests/',views.follower_request_view,name='follower_request_view'),
    path('follow_btn/<int:user_id>/',views.follow_btn_view,name='follow_btn'),
    path('follow_req_btn/<int:user_id>/',views.follow_req_btn_view,name='follow_req_btn'),
    path('posts/<str:user>/', views.posts_view,name='posts'),
    path('sharedposts/<str:user>/', views.sharedposts_view,name='sharedposts'),
    path('videos/<str:user>/', views.videos_view,name='videos'),
    path('pinnedposts/', views.pinnedposts_view,name='pinnedposts'),
    path('messenger/<str:user>', views.messenger_view,name='messenger'),
    path('messenger', views.messenger_view,name='messenger'),
    path('clear_chat/<int:chat_id>/', views.clear_chat,name='clear_chat'),
    path('load_messages/<str:user>/<int:count>/',views.load_messages,name='load_messages'),
    path('leaderboard/', views.leaderboard_view,name='leaderboard'),
    path('creategroup', views.createGroupView, name='create'),
    path('change_group_image', views.change_group_image, name='change_group_image'),
    path('notepad',views.notepadView,name='notepade'),
    path('calender',views.calenderView,name='calender'),
    path('moodcapture',views.moodCaptureView,name='mood'),
    path('getmood',views.getMoodView,name='getmood'),
    
]