# Generated by Django 3.2.2 on 2021-05-16 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u1_status', models.CharField(default='unread', max_length=10)),
                ('u2_status', models.CharField(default='unread', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('like_count', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('comment_likers', models.ManyToManyField(default=None, related_name='comment_likers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_type', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('notify_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luxverth.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
                ('caption', models.TextField()),
                ('like_count', models.IntegerField(default=0)),
                ('desc', models.TextField(default='test')),
                ('comment_count', models.IntegerField(default=0)),
                ('shared_post_count', models.IntegerField(default=0)),
                ('SharedPost', models.BooleanField(default=False)),
                ('sharedpost_caption', models.TextField(default='none')),
                ('sharedpost_desc', models.TextField(default='none')),
                ('o_post', models.IntegerField(default=0)),
                ('post_type', models.CharField(default='photo', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('comments', models.ManyToManyField(related_name='comments', to='luxverth.Comment')),
                ('liker_users', models.ManyToManyField(blank=True, default=None, null=True, related_name='likers', to=settings.AUTH_USER_MODEL)),
                ('sharedpost_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_post_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='none')),
                ('profile_image', models.TextField(default='/img/profile/default-avatar.png')),
                ('city', models.CharField(default='none', max_length=30)),
                ('country', models.CharField(default='none', max_length=30)),
                ('fav_image1', models.TextField(default='/img/profile/default-avatar.png')),
                ('fav_image2', models.TextField(default='/img/profile/default-avatar.png')),
                ('fav_image3', models.TextField(default='/img/profile/default-avatar.png')),
                ('fav_image4', models.TextField(default='/img/profile/default-avatar.png')),
                ('follower_count', models.IntegerField(default=0)),
                ('following_count', models.IntegerField(default=0)),
                ('worth', models.FloatField(default=0)),
                ('notification_bell', models.BooleanField(default=False)),
                ('phone_no', models.IntegerField(default=0)),
                ('gender', models.CharField(default='None', max_length=10)),
                ('status', models.CharField(default='Newbie', max_length=100)),
                ('message_notification_count', models.IntegerField(default=0)),
                ('privacy', models.BooleanField(default=False)),
                ('follow_requests', models.ManyToManyField(blank=True, default=None, related_name='follow_requests', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('followings', models.ManyToManyField(blank=True, related_name='followings', to=settings.AUTH_USER_MODEL)),
                ('notifications', models.ManyToManyField(blank=True, default=None, related_name='notification', to='luxverth.Notification')),
                ('pinned', models.ManyToManyField(blank=True, related_name='pinned_posts', to='luxverth.Post')),
                ('post', models.ManyToManyField(blank=True, related_name='posts', to='luxverth.Post')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='text_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='asd')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='char', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luxverth.chats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('like_count', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('reply_likers', models.ManyToManyField(default=None, related_name='reply_likers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_message',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='luxverth.text_message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luxverth.post'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luxverth.reply'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notify_user_request',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(default=None, related_name='replies', to='luxverth.Reply'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chats',
            name='last_text_message',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_message', to='luxverth.text_message'),
        ),
        migrations.AddField(
            model_name='chats',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='messages', to='luxverth.text_Message'),
        ),
        migrations.AddField(
            model_name='chats',
            name='u1_clear_chat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u1_last_delete_message', to='luxverth.text_message'),
        ),
        migrations.AddField(
            model_name='chats',
            name='u2_clear_chat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u2_last_delete_message', to='luxverth.text_message'),
        ),
        migrations.AddField(
            model_name='chats',
            name='user1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chats',
            name='user2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
