# Generated by Django 3.2.2 on 2021-05-16 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('luxverth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('group_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_admin', to=settings.AUTH_USER_MODEL)),
                ('last_text_message', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_last_message', to='luxverth.text_message')),
                ('members', models.ManyToManyField(related_name='group_members', to=settings.AUTH_USER_MODEL)),
                ('messages', models.ManyToManyField(blank=True, related_name='group_messages', to='luxverth.text_Message')),
            ],
        ),
    ]
